### ISSUE TITLE
TypeError: Assignment to constant variable.

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#9]
I'm getting a new error when enrolling an user:

```
TypeError: Assignment to constant variable.
    at faceIO._fillParameters (fio.js:1:20508)
    at fio.js:1:22052
    at new Promise (<anonymous>)
    at faceIO.enroll (fio.js:1:21829)
    at faceio.enroll (index.js:42:34)
    at Proxy.enrollNewUser (faceio-store.ts?t=1686248276642:49:20)
    at Proxy.<anonymous> (pinia.mjs:1366:30)
    at store.<computed> (pinia.mjs:916:40)
    at onSubmit (NewEmployee.vue:138:13)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
```

<img width="695" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/adf9d00e-fcd6-489d-9d81-3a6d53ee51d6">

This error isn't even handled with any errCode.

And as a result, I can't enroll users, it was working yesterday, actually this is the second time, enrollment suddenly stops working...

_Originally posted by @NaturalDevCR in https://github.com/symisc/faceio-npm/issues/7#issuecomment-1583130183_

**Comment by symisc** [comment]
Hello,

Please wait until the update is being pushed to the NPM repository. You will see random errors during this upgrade process. That's normal. Thanks for understanding.

Symisc Systems, SUARL

-----Original Message-----
From: Josue ***@***.***>
To: symisc/faceio-npm ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Thu, 08 Jun 2023 20:11
Subject: [symisc/faceio-npm] TypeError: Assignment to constant variable. (Issue #9)

I'm getting a new error when enrolling an user:

```
TypeError: Assignment to constant variable.
    at faceIO._fillParameters (fio.js:1:20508)
    at fio.js:1:22052
    at new Promise (<anonymous>)
    at faceIO.enroll (fio.js:1:21829)
    at faceio.enroll (index.js:42:34)
    at Proxy.enrollNewUser (faceio-store.ts?t=1686248276642:49:20)
    at Proxy.<anonymous> (pinia.mjs:1366:30)
    at store.<computed> (pinia.mjs:916:40)
    at onSubmit (NewEmployee.vue:138:13)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
```

<img width="695" alt="image" src="https://github.com/symisc/faceio-npm/assets/35145882/adf9d00e-fcd6-489d-9d81-3a6d53ee51d6">

This error isn't even handled with any errCode.

And as a result, I can't enroll users, it was working yesterday, actually this is the second time, enrollment suddenly stops working...

_Originally posted by @NaturalDevCR in https://github.com/symisc/faceio-npm/issues/7#issuecomment-1583130183_
            

-- 
Reply to this email directly or view it on GitHub:
https://github.com/symisc/faceio-npm/issues/9

**Comment by symisc** [comment]
Issue has been resolved now the upgrade process is done.
